---
pdns_backends_sqlite3_databases:
  - '/var/lib/pdns/pdns.sqlite3'

pdns_repo_provider: 'powerdns'
pdns_repo_branch: '40'
pdns_backends:
  gsqlite3:
    database: '/var/lib/pdns/pdns.sqlite3'
    dnssec: yes

pdns_config:
  master: yes
  local-address: "{{ansible_default_ipv4['address']}}"
  local-ipv6: "{{ansible_default_ipv6['address']}}"
  allow-axfr-ips: '188.166.104.87, 2a03:b0c0:2:d0::4af:b001, 45.55.10.200, 2604:a880:1:20::132:5001'
  api: yes
  api-key: "{{pdns_api_password}}"
  webserver: yes
  webserver-allow-from: '127.0.0.0/8'
