---

- name: Include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install role dependencies
  package: name="{{ item }}" state=present
  with_items: "{{ common_role_dependencies }}"

- name: check that sudo does not require a tty
  lineinfile:
    dest: /etc/sudoers
    regexp: '^Defaults\s+requiretty'
    state: absent

- include: root-passwd.yml
- include: extras.yml
