---

- name: Disable SSH root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: "PermitRootLogin no"
  notify: reload sshd

- name: Disable SSH PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: "PasswordAuthentication no"
  notify: reload sshd

- name: Delete SSH 'root' user keys
  file: name=/root/.ssh/authorized_keys state=absent
