---
# This playbook just provisions the users
- name: Configure the SSH users, sudo and other common things
  hosts: all
  become: true
  become_user: root
  tags:
    - common
  roles:
    - { role: common,
        users: "{{ nlnog_users }}",
        user_groups: "{{ nlnog_groups }}" }
