
- include: load_vars.yml

- name: Configure the SSH users, sudo and other common things
  hosts: all
  remote_user: "{{remote_user}}"
  become: "{{become}}"
  become_user: root
  tags:
    - common
  roles:
    - role: common
      users: "{{ nlnog_users }}"
      user_groups: "{{ nlnog_groups }}"

